"""Pre-flight validation results.

Adapters inspect a case and return a :class:`ValidationReport`: a list of findings, each
with a severity. The daemon does not interpret the findings; it only asks whether any
reach ERROR, which blocks submission unless the user explicitly forces it.

That override exists because the user knows things the validator does not -- a mesh
generated by a step the adapter cannot see, a solver installed somewhere unusual. A
validator that cannot be overridden eventually gets worked around by not using Dispatch.
"""

from __future__ import annotations

from collections.abc import Iterator, Sequence
from dataclasses import dataclass, field
from enum import IntEnum

__all__ = ["Finding", "Severity", "ValidationReport"]


class Severity(IntEnum):
    """How serious a finding is.

    :class:`IntEnum` so severities compare and sort naturally, and ``max()`` over a
    report yields the worst one.
    """

    INFO = 10
    """Something the user should know, which is not a problem.

    "Existing decomposition is 8, requested 20 -- the case will be re-decomposed" is the
    canonical example: expected, automatic, and worth saying out loud before it happens.
    """

    WARNING = 20
    """Probably wrong, but plausibly intentional. Does not block submission."""

    ERROR = 30
    """The job will not work. Blocks submission unless forced."""

    @property
    def label(self) -> str:
        """Short uppercase name for display."""
        return self.name


@dataclass(frozen=True, slots=True)
class Finding:
    """A single validation result.

    Attributes:
        severity: How serious this is.
        message: What is wrong, in the user's terms.
        hint: Optional suggested remedy. Kept separate from ``message`` so the TUI can
            de-emphasise it and the CLI can omit it in compact output.
        path: Optional file or directory the finding concerns, for jump-to-file.
        code: Stable machine-readable identifier, e.g. ``missing_controldict``. Lets
            tests assert on findings without matching prose.
    """

    severity: Severity
    message: str
    hint: str | None = None
    path: str | None = None
    code: str = ""

    def __str__(self) -> str:
        return f"{self.severity.label}: {self.message}"


@dataclass(frozen=True, slots=True)
class ValidationReport:
    """The complete result of validating one case."""

    findings: Sequence[Finding] = field(default_factory=tuple)

    def __iter__(self) -> Iterator[Finding]:
        return iter(self.findings)

    def __len__(self) -> int:
        return len(self.findings)

    def __bool__(self) -> bool:
        """A report is truthy when it contains findings, empty or not passing."""
        return bool(self.findings)

    @property
    def worst(self) -> Severity | None:
        """The highest severity present, or ``None`` for a clean report."""
        return max((f.severity for f in self.findings), default=None)

    @property
    def passed(self) -> bool:
        """Whether the case may be submitted without an explicit override."""
        return self.worst is None or self.worst < Severity.ERROR

    def of(self, severity: Severity) -> Sequence[Finding]:
        """Findings at exactly ``severity``."""
        return tuple(f for f in self.findings if f.severity is severity)

    @property
    def errors(self) -> Sequence[Finding]:
        """Blocking findings."""
        return self.of(Severity.ERROR)

    def summary(self) -> str:
        """One-line result, e.g. ``PASS (1 note)`` or ``FAIL (2 errors, 1 warning)``."""
        if not self.findings:
            return "PASS"
        counts = {s: len(self.of(s)) for s in Severity}
        pieces: list[str] = []
        if counts[Severity.ERROR]:
            pieces.append(_plural(counts[Severity.ERROR], "error"))
        if counts[Severity.WARNING]:
            pieces.append(_plural(counts[Severity.WARNING], "warning"))
        if counts[Severity.INFO]:
            pieces.append(_plural(counts[Severity.INFO], "note"))
        return f"{'PASS' if self.passed else 'FAIL'} ({', '.join(pieces)})"

    @classmethod
    def merge(cls, *reports: ValidationReport) -> ValidationReport:
        """Combine several reports, preserving order."""
        merged: list[Finding] = []
        for report in reports:
            merged.extend(report.findings)
        return cls(tuple(merged))


class ReportBuilder:
    """Convenience accumulator for adapters writing a validation method.

    Keeps adapter code reading as a checklist rather than as list manipulation::

        b = ReportBuilder()
        if not (case / "system" / "controlDict").exists():
            b.error("system/controlDict is missing", code="missing_controldict")
        return b.build()
    """

    __slots__ = ("_findings",)

    def __init__(self) -> None:
        self._findings: list[Finding] = []

    def add(
        self,
        severity: Severity,
        message: str,
        *,
        hint: str | None = None,
        path: str | None = None,
        code: str = "",
    ) -> None:
        """Append a finding at an explicit severity."""
        self._findings.append(Finding(severity, message, hint=hint, path=path, code=code))

    def info(self, message: str, **kw: str | None) -> None:
        """Append an INFO finding."""
        self.add(Severity.INFO, message, **kw)  # type: ignore[arg-type]

    def warning(self, message: str, **kw: str | None) -> None:
        """Append a WARNING finding."""
        self.add(Severity.WARNING, message, **kw)  # type: ignore[arg-type]

    def error(self, message: str, **kw: str | None) -> None:
        """Append an ERROR finding."""
        self.add(Severity.ERROR, message, **kw)  # type: ignore[arg-type]

    def build(self) -> ValidationReport:
        """Return the accumulated report."""
        return ValidationReport(tuple(self._findings))


def _plural(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"
