"""Detection, validation, and planning without side effects.

Every path that submits a job goes through :class:`CaseInspector`. ``--dry-run`` uses the
same code and stops before the final step, so what the user is shown is generated by the
code that will run rather than by a description of it.

This is essentially free because adapters return plans as *data*. Had adapters spawned
their own processes, dry run would have needed a parallel no-op implementation of every
adapter -- and it would have drifted from the real one within a release.
"""

from __future__ import annotations

import contextlib
import logging
import os
from collections.abc import Sequence
from pathlib import Path

from dispatch.adapters.base import CaseContext, SolverAdapter
from dispatch.adapters.registry import AdapterRegistry
from dispatch.core.errors import AdapterError, ValidationError
from dispatch.core.metadata import CaseMetadata
from dispatch.core.models import Detection
from dispatch.core.plan import DryRunReport, ExecutionPlan, ResourceProjection
from dispatch.core.validation import ReportBuilder, ValidationReport
from dispatch.daemon.resources import ResourceModel

__all__ = ["CaseInspector", "InspectionResult"]

log = logging.getLogger(__name__)


class InspectionResult:
    """What inspecting a directory produced, before anything was written down."""

    __slots__ = ("adapter", "context", "detection", "detections", "metadata", "plan", "report")

    def __init__(
        self,
        *,
        detections: Sequence[Detection],
        detection: Detection | None,
        adapter: SolverAdapter,
        context: CaseContext | None,
        report: ValidationReport,
        plan: ExecutionPlan | None,
        metadata: CaseMetadata | None,
    ) -> None:
        self.detections = detections
        self.detection = detection
        self.adapter = adapter
        self.context = context
        self.report = report
        self.plan = plan
        self.metadata = metadata


class CaseInspector:
    """Runs the detect, validate, plan sequence against a directory.

    Args:
        registry: Adapters.
        resources: Ledger, used only to project whether a job would start immediately.
    """

    def __init__(self, *, registry: AdapterRegistry, resources: ResourceModel) -> None:
        self._registry = registry
        self._resources = resources

    def detect(self, path: Path) -> Sequence[Detection]:
        """Ask every adapter whether ``path`` is its kind of case."""
        return self._registry.detect(self._resolve(path))

    def inspect(
        self,
        path: Path,
        *,
        cores: int = 1,
        ram_mb: int | None = None,
        solver: str | None = None,
        entry: Path | None = None,
        job_name: str = "",
        build_plan: bool = True,
    ) -> InspectionResult:
        """Detect, validate, and optionally plan, touching nothing.

        Args:
            solver: Force a specific adapter. When ``None``, detection decides -- and if it
                is unambiguous, the user is never asked.
            build_plan: Whether to build the execution plan. Skipped for a plain validation
                request, where the commands are not needed.

        Raises:
            ValidationError: If the directory does not exist, or no adapter recognises it,
                or two adapters recognise it equally well.
        """
        workdir = self._resolve(path)
        if not workdir.is_dir():
            raise ValidationError(f"{workdir} is not a directory", detail={"path": str(workdir)})

        detections = self._registry.detect(workdir)
        chosen = self._choose(workdir, detections, solver)
        adapter = self._registry.get(chosen.solver)

        ctx = self._context(
            workdir,
            adapter=adapter,
            solver=chosen.solver,
            cores=cores,
            ram_mb=ram_mb,
            entry=entry or chosen.entry,
            job_name=job_name,
        )

        report = self._validate(adapter, ctx)
        metadata = self._collect(adapter, ctx)
        if metadata is not None:
            ctx = _with_metadata(ctx, metadata)

        plan: ExecutionPlan | None = None
        if build_plan and report.passed:
            plan = self._plan(adapter, ctx)

        return InspectionResult(
            detections=detections,
            detection=chosen,
            adapter=adapter,
            context=ctx,
            report=report,
            plan=plan,
            metadata=metadata,
        )

    def dry_run(
        self,
        path: Path,
        *,
        cores: int = 1,
        ram_mb: int | None = None,
        solver: str | None = None,
        entry: Path | None = None,
        job_name: str = "",
    ) -> DryRunReport:
        """Produce the full report ``--dry-run`` prints. Nothing is created or started."""
        result = self.inspect(
            path,
            cores=cores,
            ram_mb=ram_mb,
            solver=solver,
            entry=entry,
            job_name=job_name,
            build_plan=True,
        )
        assert result.detection is not None and result.context is not None

        suggested: Sequence[str] = ()
        with contextlib.suppress(Exception):
            suggested = tuple(result.adapter.suggest_tags(result.context))

        from dispatch.core.models import ResourceRequest

        request = ResourceRequest(cores=cores, ram_mb=ram_mb)
        can, reason = self._resources.can_admit(request)

        return DryRunReport(
            workdir=result.context.workdir,
            solver=result.detection.solver,
            solver_binary=result.detection.solver_binary,
            cores=cores,
            detections=result.detections,
            validation=result.report,
            plan=result.plan,
            suggested_tags=suggested,
            projection=ResourceProjection(
                cores_requested=cores,
                cores_free=self._resources.free_cores,
                cores_total=self._resources.total_cores,
                would_start_immediately=can,
                blocking_reason=reason,
            ),
        )

    # -- internals ---------------------------------------------------------------------------

    def _resolve(self, path: Path) -> Path:
        return Path(path).expanduser().resolve()

    def _choose(
        self, workdir: Path, detections: Sequence[Detection], solver: str | None
    ) -> Detection:
        """Pick the adapter, or explain why the user has to."""
        if solver:
            if solver not in self._registry:
                raise AdapterError(
                    f"No solver adapter named {solver!r}. "
                    f"Registered: {', '.join(self._registry.names) or 'none'}"
                )
            for detection in detections:
                if detection.solver == solver:
                    return detection
            # The user asked for an adapter that did not volunteer. Honour it -- they may
            # know something the detector does not -- but with no claimed confidence.
            return Detection(solver=solver, confidence=0.0, label="chosen by the user")

        if not detections:
            raise ValidationError(
                f"No solver recognised {workdir}. Checked: "
                f"{', '.join(self._registry.names) or 'no adapters registered'}. "
                "Choose one explicitly if you know which it is.",
                detail={"path": str(workdir), "adapters": list(self._registry.names)},
            )

        best = self._registry.best_detection(workdir)
        if best is not None:
            return best

        names = ", ".join(f"{d.solver} ({d.confidence:.2f})" for d in detections)
        raise ValidationError(
            f"More than one solver could handle {workdir}: {names}. Choose one explicitly.",
            detail={"candidates": [d.solver for d in detections]},
        )

    def _context(
        self,
        workdir: Path,
        *,
        adapter: SolverAdapter,
        solver: str,
        cores: int,
        ram_mb: int | None,
        entry: Path | None,
        job_name: str,
    ) -> CaseContext:
        base = self._registry.context(
            workdir,
            cores=cores,
            ram_mb=ram_mb,
            entry=entry,
            env=dict(os.environ),
            adapter=solver,
            job_name=job_name,
        )
        try:
            env = adapter.prepare_environment(base)
        except Exception as exc:
            log.warning("Adapter %s could not prepare its environment: %s", solver, exc)
            return base
        return CaseContext(
            workdir=base.workdir,
            cores=base.cores,
            ram_mb=base.ram_mb,
            entry=base.entry,
            env=dict(env),
            settings=base.settings,
            job_name=base.job_name,
        )

    def _validate(self, adapter: SolverAdapter, ctx: CaseContext) -> ValidationReport:
        """Run the adapter's checks, turning an adapter crash into a finding.

        A validator that raises must not become a traceback in the submit wizard; it
        becomes an ERROR the user can read and, if they disagree, override.
        """
        try:
            return adapter.validate(ctx)
        except Exception as exc:
            log.exception("Adapter validation failed")
            builder = ReportBuilder()
            builder.error(
                f"The {getattr(adapter, 'display_name', 'solver')} adapter failed while "
                f"checking this case: {exc}",
                code="adapter_error",
            )
            return builder.build()

    def _plan(self, adapter: SolverAdapter, ctx: CaseContext) -> ExecutionPlan | None:
        try:
            return adapter.plan(ctx)
        except Exception as exc:
            log.exception("Adapter planning failed")
            raise ValidationError(
                f"Could not build an execution plan for this case: {exc}"
            ) from exc

    def _collect(self, adapter: SolverAdapter, ctx: CaseContext) -> CaseMetadata | None:
        try:
            return adapter.collect_metadata(ctx)
        except Exception as exc:
            log.warning("Adapter could not collect metadata: %s", exc)
            return None


def _with_metadata(ctx: CaseContext, metadata: CaseMetadata) -> CaseContext:
    return CaseContext(
        workdir=ctx.workdir,
        cores=ctx.cores,
        ram_mb=ctx.ram_mb,
        entry=ctx.entry,
        env=ctx.env,
        settings=ctx.settings,
        job_name=ctx.job_name,
        metadata=metadata,
    )
